### ISSUE TITLE
Any software able to provide db.sqlite3 visualization + data manipulation

### ISSUE THREAD

**Issue by damianpetroff** [HE-Arc/OpenSauce#16]
Any good tool for that ?

PyCharm does that, but the we'll not be using the whole IDE just for this.

**Comment by Ishydo** [comment]
Si c'est pour avoir un UI afin de chercker vos données, il y a ça qui est léger et efficace
https://sqlitebrowser.org/dl/

N'oubliez pas que sqlite est une DB _file based_ et qu'elle ne permet pas de _user management_. ça pourrait vous poser problème (ou pas? à voir selon vos besoins) pour la suite (mais pas d'inquiétude la passage éventuel d'un DB engine à un autre est très facile avec les frameworks comme django).

https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems
