### ISSUE TITLE
Get specifications approval

### ISSUE THREAD

**Issue by damianpetroff** [HE-Arc/OpenSauce#3]
Les spécifications sont disponibles à l'adresse suivante :  https://github.com/HE-Arc/OpenSauce/wiki/Cahier-des-charges

@grunenwald est-il possible pour vous de les commenter ou d'ajouter des recommandations si besoin est, et si vous avez des questions n'hésitez pas à les poser.

**Comment by grunenwald** [comment]
Comment répond-on aux questions ? (choix multiple ? plusieurs réponses possibles ? réponse texte ?)
Comment est déterminé un jeu de questions (fait à la main suivant un thème donné ? tiré au hasard parmi une liste ?)
Durée d'une partie ? Comment elle démarre/termine ? Voit-on les réponses des autres en temps réel ? Peut-on jouer seul ? (sinon nb min players)
...
faire des maquettes et vous mettre en situation de jeu vous aidera à le compléter (... et plus il est sera complet, moins vous aurez à vous poser de questions en cours de dev)


Pour les contraintes techniques, vous pouvez ajouter la relation n-n

**Comment by damianpetroff** [comment]
Merci pour ces précisions, le cahier des charges a été mis à jour.
